### PR TITLE
revert Rake version requirement

### PR DESCRIPTION
**Pull request by colinsurprenant**
not needed anymore.

### CODE REVIEW

**Comment by purbon** [comment]
Two easy questions:

1.- There is no version bump, why?
2.- Why is not need anymore?

- purbon

**Comment by purbon** [comment]
Otherwise looks good and simple, like PR with more red than green!!

**Comment by colinsurprenant** [comment]
because I forgot the version bump in the previous PR and we did not publish so I figured I'd not bump this one either since we don't need publishing...

it was not needed in the first place, the problem is not related to the rake version specification here.

**Comment by jsvd** [comment]
LGTM

**Comment by colinsurprenant** [comment]
since we published devutils before we merged this PR I now need to bump the version number and republish.

**Pull request closed without merging**
